#ifndef ROSAFESTRUCT_IDL
#define ROSAFESTRUCT_IDL

#define MAX_STRING_LENGTH 500

module rosAFE {	

    struct timestamp
    {
        unsigned long sec;
        unsigned long usec; // should be nsec
    };

    struct std_msgs__Header
    {
        unsigned long seq;
        timestamp stamp;
    };

    struct signalOneD
    {
        sequence<double>       	    data;
    };

    struct signalND
    {
        sequence<signalOneD >       dataN;
    };

    struct TimeDomainSignalPortStruct {
        unsigned long 			sampleRate;
        unsigned long long    		lastFrameIndex;
        unsigned long long    		framesOnPort;
        signalOneD	      		left;
        signalOneD	      		right;
    };

    struct TimeFrequencySignalPortStruct {
        unsigned long 			sampleRate;
        unsigned long long    		lastFrameIndex;
        unsigned long long    		framesOnPort;
        unsigned long         		numberOfChannels;
        signalND      	      		left;
        signalND              		right;
    };

    struct infos {
       unsigned long sampleRate;
       unsigned long bufferSize_s;
       unsigned long innerBufferSize_s;
    };

    struct inputProcsParametres {
      string name;
      boolean in_doNormalize;
      unsigned long long in_normalizeValue;
    };

    struct preProcsParametres {
      string name;
      string upperDepName;
      boolean pp_bRemoveDC;
      double pp_cutoffHzDC;
      boolean pp_bPreEmphasis;
      double pp_coefPreEmphasis;
      boolean pp_bNormalizeRMS;
      double pp_intTimeSecRMS;
      boolean pp_bLevelScaling;
      double pp_refSPLdB;
      boolean pp_bMiddleEarFiltering;
      string pp_middleEarModel;
      boolean pp_bUnityComp;
    };

    struct gammatoneProcsParametres {
      string name;
      string upperDepName;
      string fb_type;
      double fb_lowFreqHz;
      double fb_highFreqHz;
      double fb_nERBs;
      unsigned long fb_nChannels;
      sequence<double> fb_cfHz;
      unsigned long fb_nGamma;
      double fb_bwERBs;
    };

    struct ihcProcsParametres {
      string name;
      string upperDepName;
      string ihc_method;
    };

    struct ildProcsParametres {
      string name;
      string upperDepName;
      string ild_wname;
      double ild_wSizeSec;
      double ild_hSizeSec;
    };

    struct parameters {
      sequence<inputProcsParametres> 		input;
      sequence<preProcsParametres>      	preProc;
      sequence<gammatoneProcsParametres>        gammatone;
      sequence<ihcProcsParametres>      	ihc;
      sequence<ildProcsParametres>      	ild;
    };

    struct dataObjSt {
      unsigned long         			sampleRate;
      sequence<TimeDomainSignalPortStruct>	allTDSPorts;
      sequence<TimeFrequencySignalPortStruct>	allTFSPorts;
    };
};



#endif /* ROSAFESTRUCT_IDL */

