#ifndef ROSAFESTRUCT_IDL
#define ROSAFESTRUCT_IDL

#define MAX_STRING_LENGTH 500

module rosAFE {	

    struct timestamp
    {
        unsigned long sec;
        unsigned long usec; // should be nsec
    };

    struct std_msgs__Header
    {
        unsigned long seq;
        timestamp stamp;
    };

    struct signalOneD
    {
        sequence<float>       	    data;
    };

    struct signalND
    {
        sequence<signalOneD >       dataN;
    };

    struct TimeDomainSignalPortStruct {
        unsigned long 			sampleRate;
        unsigned long long    		lastFrameIndex;
        unsigned long long    		framesOnPort;
        signalOneD	      		left;
        signalOneD	      		right;
    };

    struct TimeFrequencySignalPortStruct {
        string<MAX_STRING_LENGTH> 	name;
        unsigned long long    		lastFrameIndex;
        unsigned long long    		lostData;
        unsigned long long    		framesOnPort;
        unsigned long         		numberOfChannels;
        signalND      	      		left;
        signalND              		right;
    };

    struct infos {
       unsigned long sampleRate;
       unsigned long bufferSize_s;
       unsigned long innerBufferSize_s;
    };

    struct inputProcsParametres {
      string name;
    };

    struct preProcsParametres {
      string name;
      string upperDepName;
      unsigned long fsOut;
      unsigned short pp_bRemoveDC;
      float pp_cutoffHzDC;
      unsigned short pp_bPreEmphasis;
      float pp_coefPreEmphasis;
      unsigned short pp_bNormalizeRMS;
      unsigned short pp_bBinauralRMS;
      float pp_intTimeSecRMS;
      unsigned short pp_bLevelScaling;
      float pp_refSPLdB;
      unsigned short pp_bMiddleEarFiltering;
      string pp_middleEarModel;
      unsigned short pp_bUnityComp;
    };

    struct gammatoneProcsParametres {
      string name;
      string upperDepName;
      unsigned long fsOut;
      string fb_type;
      float fb_lowFreqHz;
      float fb_highFreqHz;
      float fb_nERBs;
      unsigned long fb_nChannels;
      unsigned long fb_cfHz;
      unsigned long fb_nGamma;
      float fb_bwERBs;
    };

    struct ihcProcsParametres {
      string name;
      string upperDepName;
      unsigned long fsOut;
      string ihc_method;
    };

    struct ildProcsParametres {
      string name;
      string upperDepName;
      unsigned long fsOut;
      string ild_wname;
      float ild_wSizeSec;
      float ild_hSizeSec;
    };

    struct RunningProcessorsSt {
      std_msgs__Header header;
      sequence<inputProcsParametres> 		paramsInputProc;
      sequence<preProcsParametres>      	paramsPreProc;
      sequence<gammatoneProcsParametres>        paramsGammatoneProc;
      sequence<ihcProcsParametres>      	paramsIhcProc;
      sequence<ildProcsParametres>      	paramsIldProc;
    };

    struct dataObjSt {
      std_msgs__Header 				header;
      unsigned long         			sampleRate;
      sequence<TimeDomainSignalPortStruct>	allTDSPorts;
      sequence<TimeFrequencySignalPortStruct>	allTFSPorts;
    };
};



#endif /* ROSAFESTRUCT_IDL */

