#ifndef ROSAFESTRUCT_IDL
#define ROSAFESTRUCT_IDL

module rosAFE {
    struct TimeDomainSignalPortStruct {
        unsigned long         sampleRate;
        unsigned long         nChunksOnPort;
        unsigned long         nFramesPerChunk;
        unsigned long long    lastFrameIndex;
        sequence<double>      left;
        sequence<double>      right;
    };
};

#endif /* ROSAFESTRUCT_IDL */
